name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build -t react-docker-learning/tests -f ./frontend/Dockerfile.dev ./frontend/
        docker run -e CI=true react-docker-learning npm run test
